id: P15C907A4
initial_creation_type: input
source_metadata:
  title: Sakya Series
  language: en
  description: 'Texts related to the Sakya (sa skya) tradition and its sub-branches:'
  volume:
    9a6bfd2c3b1a44c4bd0a19a9e47503d2:
      title: 'The Pellucid Mirror: Behavioural Guidelines for the Saṅgha'
      parent: Behavioural Guidelines
    012add88d00b416c87a57868945e8dbc:
      title: Aspiration to Follow the Gurus of the Ngor Tradition
      parent: Prayers
    45728e719af64168932317c297d80232:
      title: Prayer to the Supremely Learned Holders of the Glorious Sakya Teachings
      parent: Prayers
    4bdc3b5155ec465c8c0534880a00e2da:
      title: Prayer to Root and Lineage Masters, and the Assembly of Deity, Ḍākinīs
        and Dharma Protectors of the Sakya Lineage
      parent: Prayers
created_at: '2022-03-01T05:38:23.401064'
last_modified_at: '2022-03-01T05:38:23.401070'
